// admin-src/src/components/ConfirmDialog.vue
<script setup>
import AppIcon from './AppIcon.vue';
import { confirmState, resolveConfirm } from '../services/confirm';
</script>
<template>
  <div v-if="confirmState.open" class="modal-backdrop confirm-backdrop" @click.self="resolveConfirm(false)"><section class="modal-card confirm-dialog" role="alertdialog" aria-modal="true"><div class="confirm-icon" :class="{ danger: confirmState.danger }"><AppIcon :name="confirmState.danger ? 'AlertTriangle' : 'Info'" :size="22" /></div><div><h2>{{ confirmState.title }}</h2><p>{{ confirmState.message }}</p></div><div class="modal-actions"><button class="btn btn-ghost" @click="resolveConfirm(false)">取消</button><button class="btn" :class="confirmState.danger ? 'btn-danger' : 'btn-primary'" @click="resolveConfirm(true)">{{ confirmState.confirmText }}</button></div></section></div>
</template>

// admin-src/src/components/ConfirmDialog.tsx
import { useSyncExternalStore } from 'react';
import { AlertTriangle, Info } from 'lucide-react';

import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogMedia,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import {
  getConfirmSnapshot,
  resolveConfirm,
  subscribeConfirm,
} from '@/services/confirm';

export function ConfirmDialog() {
  const state = useSyncExternalStore(subscribeConfirm, getConfirmSnapshot, getConfirmSnapshot);

  return (
    <AlertDialog
      open={state.open}
      onOpenChange={(open) => {
        if (!open) resolveConfirm(false);
      }}
    >
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogMedia
            className={state.danger ? 'bg-destructive/10 text-destructive' : 'bg-primary/10 text-primary'}
          >
            {state.danger ? <AlertTriangle /> : <Info />}
          </AlertDialogMedia>
          <AlertDialogTitle>{state.title}</AlertDialogTitle>
          <AlertDialogDescription>{state.message}</AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel onClick={() => resolveConfirm(false)}>取消</AlertDialogCancel>
          <AlertDialogAction
            variant={state.danger ? 'destructive' : 'default'}
            onClick={() => resolveConfirm(true)}
          >
            {state.confirmText}
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}
