// admin-src/src/pages/AdminLockSettings.tsx
import { useEffect, useState } from "react"
import { Eye, EyeOff, LockKeyhole, ShieldCheck } from "lucide-react"
import { toast } from "sonner"

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Skeleton } from "@/components/ui/skeleton"
import { Switch } from "@/components/ui/switch"
import { get, post } from "@/services/http"

interface LockSettings {
  enabled: boolean
  ttl_minutes: number
  password_a_set: boolean
  password_b_set: boolean
}

interface LockForm {
  enabled: boolean
  ttl_minutes: number
  current_password: string
  password_a: string
  password_a_confirmation: string
  password_b: string
  password_b_confirmation: string
}

const initialForm: LockForm = {
  enabled: true,
  ttl_minutes: 480,
  current_password: "",
  password_a: "",
  password_a_confirmation: "",
  password_b: "",
  password_b_confirmation: "",
}

function PasswordInput({ id, label, value, placeholder, hint, visible, onChange }: {
  id: string
  label: string
  value: string
  placeholder: string
  hint?: string
  visible: boolean
  onChange: (value: string) => void
}) {
  return (
    <div className="space-y-2">
      <Label htmlFor={id}>{label}</Label>
      <Input
        id={id}
        type={visible ? "text" : "password"}
        value={value}
        autoComplete="new-password"
        placeholder={placeholder}
        onChange={(event) => onChange(event.target.value)}
      />
      {hint && <p className="text-xs text-muted-foreground">{hint}</p>}
    </div>
  )
}

export default function AdminLockSettings() {
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [visible, setVisible] = useState(false)
  const [state, setState] = useState<LockSettings>({ enabled: true, ttl_minutes: 480, password_a_set: false, password_b_set: false })
  const [form, setForm] = useState<LockForm>(initialForm)

  const patch = <K extends keyof LockForm>(key: K, value: LockForm[K]) => setForm((current) => ({ ...current, [key]: value }))

  const load = async () => {
    setLoading(true)
    try {
      const data = await get<LockSettings>("/admin-lock/settings")
      setState(data)
      setForm((current) => ({ ...current, enabled: Boolean(data.enabled), ttl_minutes: Number(data.ttl_minutes || 480) }))
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "访问锁设置加载失败")
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { void load() }, [])

  const save = async () => {
    if (form.password_a && form.password_a.length < 8) return toast.error("访问密码 A 至少需要 8 位")
    if (form.password_b && form.password_b.length < 12) return toast.error("访问密码 B 至少需要 12 位")
    if (form.password_a && form.password_a !== form.password_a_confirmation) return toast.error("两次输入的访问密码 A 不一致")
    if (form.password_b && form.password_b !== form.password_b_confirmation) return toast.error("两次输入的访问密码 B 不一致")
    if (form.password_a && form.password_b && form.password_a === form.password_b) return toast.error("两个访问密码不能相同")
    if (!form.current_password) return toast.error("请输入当前访问密码 B 以确认修改")

    setSaving(true)
    try {
      const result = await post<{ requires_unlock?: boolean }>("/admin-lock/settings", {
        enabled: form.enabled,
        ttl_minutes: Number(form.ttl_minutes),
        current_password: form.current_password,
        password_a: form.password_a || null,
        password_b: form.password_b || null,
      })
      setForm((current) => ({ ...current, current_password: "", password_a: "", password_a_confirmation: "", password_b: "", password_b_confirmation: "" }))
      toast.success(result.requires_unlock ? "设置已保存，请使用新密码重新验证" : "访问锁设置已保存")
      if (result.requires_unlock) {
        window.setTimeout(() => window.dispatchEvent(new CustomEvent("admin:locked", { detail: "locked" })), 700)
      } else {
        await load()
      }
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "保存失败")
    } finally {
      setSaving(false)
    }
  }

  if (loading) {
    return <div className="space-y-5 p-4 md:p-6"><Skeleton className="h-20 w-full" /><div className="grid gap-5 lg:grid-cols-2"><Skeleton className="h-72" /><Skeleton className="h-72" /></div></div>
  }

  return (
    <div className="space-y-6 p-4 md:p-6 lg:p-8">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">后台访问锁</h1>
        <p className="mt-1 text-sm text-muted-foreground">管理登录后的二次访问验证与有效时间。</p>
      </div>

      <Card>
        <CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center">
          <span className="grid size-11 place-items-center rounded-2xl bg-primary/10 text-primary"><LockKeyhole /></span>
          <div className="min-w-0 flex-1">
            <CardTitle className="text-base">二次访问保护</CardTitle>
            <CardDescription className="mt-1">管理员登录后，仍需通过访问密码验证才能进入受保护页面。</CardDescription>
          </div>
          <div className="flex items-center gap-3">
            <Switch checked={form.enabled} onCheckedChange={(checked) => patch("enabled", checked)} aria-label="启用后台访问锁" />
            <span className="text-sm font-medium">{form.enabled ? "已启用" : "已关闭"}</span>
          </div>
        </CardContent>
      </Card>

      <div className="grid gap-5 lg:grid-cols-2">
        <Card>
          <CardHeader className="flex-row items-start justify-between space-y-0">
            <div><CardTitle className="text-lg">访问凭证 A</CardTitle><CardDescription>用于常规受保护页面的访问验证。</CardDescription></div>
            <Badge variant={state.password_a_set ? "default" : "secondary"}>{state.password_a_set ? "已设置" : "未设置"}</Badge>
          </CardHeader>
          <CardContent className="space-y-4">
            <PasswordInput id="password-a" label="新密码" value={form.password_a} placeholder="留空表示不修改" hint="至少 8 位，且不能与另一访问凭证相同。" visible={visible} onChange={(value) => patch("password_a", value)} />
            <PasswordInput id="password-a-confirm" label="确认新密码" value={form.password_a_confirmation} placeholder="再次输入新密码" visible={visible} onChange={(value) => patch("password_a_confirmation", value)} />
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex-row items-start justify-between space-y-0">
            <div><CardTitle className="text-lg">访问凭证 B</CardTitle><CardDescription>用于需要更高权限的管理操作验证。</CardDescription></div>
            <Badge variant={state.password_b_set ? "default" : "secondary"}>{state.password_b_set ? "已设置" : "未设置"}</Badge>
          </CardHeader>
          <CardContent className="space-y-4">
            <PasswordInput id="password-b" label="新密码" value={form.password_b} placeholder="留空表示不修改" hint="至少 12 位，建议使用随机强密码。" visible={visible} onChange={(value) => patch("password_b", value)} />
            <PasswordInput id="password-b-confirm" label="确认新密码" value={form.password_b_confirmation} placeholder="再次输入新密码" visible={visible} onChange={(value) => patch("password_b_confirmation", value)} />
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader className="flex-row items-start justify-between space-y-0">
          <div><CardTitle className="text-lg">验证策略</CardTitle><CardDescription>修改凭证后，现有管理员的验证状态会立即失效。</CardDescription></div>
          <Button type="button" variant="ghost" size="sm" onClick={() => setVisible((value) => !value)}>{visible ? <EyeOff /> : <Eye />}{visible ? "隐藏密码" : "显示密码"}</Button>
        </CardHeader>
        <CardContent className="space-y-5">
          <div className="grid gap-4 md:grid-cols-2">
            <div className="space-y-2">
              <Label>验证有效时间</Label>
              <Select value={String(form.ttl_minutes)} onValueChange={(value) => patch("ttl_minutes", Number(value))}>
                <SelectTrigger className="w-full"><SelectValue /></SelectTrigger>
                <SelectContent>{[[30, "30 分钟"], [60, "1 小时"], [240, "4 小时"], [480, "8 小时"], [720, "12 小时"], [1440, "24 小时"], [10080, "7 天"]].map(([value, label]) => <SelectItem key={value} value={String(value)}>{label}</SelectItem>)}</SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="current-password">当前访问凭证 B</Label>
              <Input id="current-password" type={visible ? "text" : "password"} value={form.current_password} autoComplete="current-password" placeholder="保存前需要验证" onChange={(event) => patch("current_password", event.target.value)} />
            </div>
          </div>
          <Alert>
            <ShieldCheck />
            <AlertTitle>凭证安全</AlertTitle>
            <AlertDescription>访问凭证只以不可逆哈希保存，页面与接口不会返回原文。</AlertDescription>
          </Alert>
          <div className="flex justify-end"><Button disabled={saving || !form.current_password} onClick={() => void save()}>{saving ? "保存中…" : "保存并应用"}</Button></div>
        </CardContent>
      </Card>
    </div>
  )
}

// admin-src/src/pages/AdminLockSettings.vue
<script setup>
import { onMounted, reactive, ref } from 'vue';
import AppIcon from '../components/AppIcon.vue';
import ToggleSwitch from '../components/ToggleSwitch.vue';
import { get, post } from '../services/http';

const loading = ref(true), saving = ref(false), reveal = ref(false);
const message = reactive({ text: '', type: 'success' });
const form = reactive({ enabled: true, ttl_minutes: 480, current_password: '', password_a: '', password_a_confirmation: '', password_b: '', password_b_confirmation: '' });
const state = reactive({ password_a_set: false, password_b_set: false });
function notify(text, type = 'success') { message.text = text; message.type = type; clearTimeout(notify.timer); notify.timer = setTimeout(() => { message.text = ''; }, 3500); }
async function load() {
  loading.value = true;
  try { const data = await get('/admin-lock/settings'); Object.assign(form, { enabled: data.enabled, ttl_minutes: data.ttl_minutes }); Object.assign(state, data); }
  catch (error) { notify(error.message, 'error'); } finally { loading.value = false; }
}
async function save() {
  if (form.password_a && form.password_a !== form.password_a_confirmation) return notify('两次输入的访问密码 A 不一致', 'error');
  if (form.password_b && form.password_b !== form.password_b_confirmation) return notify('两次输入的访问密码 B 不一致', 'error');
  if (form.password_a && form.password_b && form.password_a === form.password_b) return notify('两个访问密码不能相同', 'error');
  saving.value = true;
  try {
    const result = await post('/admin-lock/settings', { enabled: form.enabled, ttl_minutes: Number(form.ttl_minutes), current_password: form.current_password, password_a: form.password_a || null, password_b: form.password_b || null });
    form.current_password = ''; form.password_a = ''; form.password_a_confirmation = ''; form.password_b = ''; form.password_b_confirmation = '';
    notify(result.requires_unlock ? '设置已保存，请使用新密码重新解锁' : '后台访问锁已关闭');
    if (result.requires_unlock) setTimeout(() => window.dispatchEvent(new CustomEvent('admin:locked', { detail: 'locked' })), 900); else load();
  } catch (error) { notify(error.message, 'error'); } finally { saving.value = false; }
}
onMounted(load);
</script>

<template>
  <section class="page-stack lock-settings-page">
    <div class="page-heading"><span class="eyebrow">ACCESS CONTROL</span><h1>后台访问锁</h1><p>自定义二次访问密码，并控制解锁状态的有效时间。</p></div>
    <div v-if="loading" class="panel settings-loading">正在读取访问锁设置…</div>
    <template v-else>
      <section class="panel lock-status-card">
        <div class="lock-status-icon"><AppIcon name="LockKeyhole" :size="24" /></div>
        <div><h2>二次访问保护</h2><p>管理员登录成功后，仍需输入访问密码才能查看后台内容。</p></div>
        <ToggleSwitch v-model="form.enabled" on-label="保护已开启" off-label="保护已关闭" />
      </section>
      <div class="lock-settings-grid">
        <section class="panel lock-password-card">
          <div class="panel-head"><div><h2>访问密码 A</h2><p>用于日常状态验证。</p></div><span class="status-pill success">{{ state.password_a_set ? '已设置' : '未设置' }}</span></div>
          <label class="field"><span>新密码</span><input v-model="form.password_a" :type="reveal ? 'text' : 'password'" minlength="8" maxlength="128" autocomplete="new-password" placeholder="留空表示不修改" /><small>至少 8 位，不能与访问密码 B 相同。</small></label>
          <label class="field"><span>确认新密码</span><input v-model="form.password_a_confirmation" :type="reveal ? 'text' : 'password'" autocomplete="new-password" placeholder="再次输入新密码" /></label>
        </section>
        <section class="panel lock-password-card critical">
          <div class="panel-head"><div><h2>访问密码 B</h2><p>用于管理操作验证。</p></div><span class="status-pill success">{{ state.password_b_set ? '已设置' : '未设置' }}</span></div>
          <label class="field"><span>新密码</span><input v-model="form.password_b" :type="reveal ? 'text' : 'password'" minlength="12" maxlength="128" autocomplete="new-password" placeholder="留空表示不修改" /><small>至少 12 位，建议使用随机密码。</small></label>
          <label class="field"><span>确认新密码</span><input v-model="form.password_b_confirmation" :type="reveal ? 'text' : 'password'" autocomplete="new-password" placeholder="再次输入新密码" /></label>
        </section>
      </div>
      <section class="panel lock-policy-card">
        <div class="panel-head"><div><h2>解锁策略</h2><p>密码变更后，所有管理员的现有解锁状态会立即失效。</p></div><button class="btn btn-ghost btn-sm" type="button" @click="reveal = !reveal">{{ reveal ? '隐藏密码' : '显示密码' }}</button></div>
        <div class="lock-policy-form">
          <label class="field"><span>解锁有效时间</span><select v-model.number="form.ttl_minutes"><option :value="30">30 分钟</option><option :value="60">1 小时</option><option :value="240">4 小时</option><option :value="480">8 小时</option><option :value="720">12 小时</option><option :value="1440">24 小时</option><option :value="10080">7 天</option></select></label>
          <label class="field"><span>当前访问密码 B *</span><input v-model="form.current_password" :type="reveal ? 'text' : 'password'" maxlength="128" autocomplete="current-password" placeholder="保存设置前必须验证" required /><small>用于确认本次设置修改。</small></label>
        </div>
        <div class="lock-security-note"><AppIcon name="ShieldAlert" :size="19" /><span>密码仅以不可逆哈希保存，页面和接口都不会返回密码原文。关闭访问锁同样需要验证当前完整密码。</span></div>
        <div class="modal-actions"><button class="btn btn-primary" :disabled="saving || !form.current_password" @click="save">{{ saving ? '保存中…' : '保存并应用' }}</button></div>
      </section>
    </template>
    <div v-if="message.text" class="toast" :class="{ error: message.type === 'error' }">{{ message.text }}</div>
  </section>
</template>
