// admin-src/src/pages/PluginManagement.vue
<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import AppIcon from '../components/AppIcon.vue';
import SmartEditor from '../components/SmartEditor.vue';
import { get, post } from '../services/http';

const plugins = ref([]);
const types = ref([]);
const loading = ref(true);
const busyCode = ref('');
const keyword = ref('');
const typeFilter = ref('');
const statusFilter = ref('all');
const uploadInput = ref(null);
const uploading = ref(false);
const modal = reactive({ type: '', plugin: null });
const configModel = ref({});
const configFields = ref([]);
const toast = reactive({ text: '', type: 'success' });

const filtered = computed(() => plugins.value.filter((plugin) => {
  const term = keyword.value.trim().toLowerCase();
  const matchesText = !term || `${plugin.name} ${plugin.code} ${plugin.description} ${plugin.author}`.toLowerCase().includes(term);
  const matchesType = !typeFilter.value || plugin.type === typeFilter.value;
  const matchesStatus = statusFilter.value === 'all' || (statusFilter.value === 'installed' ? plugin.is_installed : !plugin.is_installed);
  return matchesText && matchesType && matchesStatus;
}));
const counts = computed(() => ({ all: plugins.value.length, installed: plugins.value.filter((item) => item.is_installed).length, enabled: plugins.value.filter((item) => item.is_enabled).length }));

function notify(text, type = 'success') { toast.text = text; toast.type = type; window.clearTimeout(notify.timer); notify.timer = window.setTimeout(() => { toast.text = ''; }, 2800); }
async function load() {
  loading.value = true;
  try { const [pluginData, typeData] = await Promise.all([get('/plugin/getPlugins'), get('/plugin/types')]); plugins.value = Array.isArray(pluginData) ? pluginData : []; types.value = Array.isArray(typeData) ? typeData : []; }
  catch (e) { notify(e.message, 'error'); } finally { loading.value = false; }
}
async function action(plugin, name, prompt = '') {
  if (prompt && !window.confirm(prompt)) return;
  busyCode.value = plugin.code;
  try { await post(`/plugin/${name}`, { code: plugin.code }); notify({ install: '安装', uninstall: '卸载', enable: '启用', disable: '禁用', upgrade: '升级', delete: '删除' }[name] + '成功'); await load(); }
  catch (e) { notify(e.message, 'error'); } finally { busyCode.value = ''; }
}
function openReadme(plugin) { modal.type = 'readme'; modal.plugin = plugin; }
function normalizeOptions(options) {
  if (Array.isArray(options)) return options.map((option) => typeof option === 'object' ? option : { value: option, label: option });
  return Object.entries(options || {}).map(([value, label]) => ({ value, label }));
}
async function openConfig(plugin) {
  busyCode.value = plugin.code;
  try {
    const config = await get('/plugin/config', { code: plugin.code });
    configModel.value = Object.fromEntries(Object.entries(config).map(([key, item]) => [key, item.value]));
    configFields.value = Object.entries(config).map(([key, item]) => ({ key, label: item.label || key, placeholder: item.placeholder, help: item.description, type: item.type === 'text' ? 'textarea' : item.type === 'string' ? 'text' : item.type, options: normalizeOptions(item.options) }));
    modal.type = 'config'; modal.plugin = plugin;
  } catch (e) { notify(e.message, 'error'); } finally { busyCode.value = ''; }
}
async function saveConfig() {
  busyCode.value = modal.plugin.code;
  try { await post('/plugin/config', { code: modal.plugin.code, config: configModel.value }); notify('插件配置已保存'); modal.type = ''; await load(); }
  catch (e) { notify(e.message, 'error'); } finally { busyCode.value = ''; }
}
async function upload(event) {
  const file = event.target.files?.[0]; if (!file) return;
  if (!file.name.toLowerCase().endsWith('.zip')) { notify('仅支持 ZIP 插件包', 'error'); event.target.value = ''; return; }
  const body = new FormData(); body.append('file', file); uploading.value = true;
  try { await post('/plugin/upload', body); notify('插件上传成功'); await load(); } catch (e) { notify(e.message, 'error'); }
  finally { uploading.value = false; event.target.value = ''; }
}
function typeName(value) { return types.value.find((item) => item.value === value)?.label || (value === 'payment' ? '支付方式' : '功能'); }
onMounted(load);
</script>

<template>
  <section class="page-stack">
    <div class="page-heading page-heading-row"><div><h1>插件管理</h1><p>安装、启用和配置功能扩展与支付插件。</p></div><div><input ref="uploadInput" hidden type="file" accept=".zip,application/zip" @change="upload" /><button class="btn btn-primary" :disabled="uploading" @click="uploadInput.click()"><AppIcon name="Upload" :size="16" />{{ uploading ? '上传中…' : '上传插件' }}</button></div></div>
    <div class="stat-grid plugin-stats"><article class="stat-card"><span>全部插件</span><strong>{{ counts.all }}</strong></article><article class="stat-card"><span>已安装</span><strong>{{ counts.installed }}</strong></article><article class="stat-card"><span>已启用</span><strong>{{ counts.enabled }}</strong></article></div>
    <div class="plugin-toolbar"><label class="filter-input"><span>搜索</span><input v-model="keyword" placeholder="插件名称、代码或描述" /></label><label class="field compact-field"><span>插件类型</span><select v-model="typeFilter"><option value="">全部类型</option><option v-for="type in types" :key="type.value" :value="type.value">{{ type.icon }} {{ type.label }}</option></select></label><label class="field compact-field"><span>安装状态</span><select v-model="statusFilter"><option value="all">全部状态</option><option value="installed">已安装</option><option value="available">可安装</option></select></label><button class="btn btn-ghost" :disabled="loading" @click="load">刷新</button></div>
    <div v-if="loading" class="panel settings-loading">正在加载插件…</div>
    <div v-else-if="!filtered.length" class="panel settings-loading">没有符合条件的插件</div>
    <div v-else class="plugin-grid">
      <article v-for="plugin in filtered" :key="plugin.code" class="panel plugin-card">
        <div class="plugin-card-head"><div class="plugin-icon"><AppIcon :name="plugin.type === 'payment' ? 'CreditCard' : 'Puzzle'" :size="23" /></div><div class="plugin-identity"><div><h2>{{ plugin.name }}</h2><span>v{{ plugin.version }}</span></div><code>{{ plugin.code }}</code></div><span class="status-pill" :class="{ off: !plugin.is_enabled }">{{ !plugin.is_installed ? '未安装' : plugin.is_enabled ? '已启用' : '已禁用' }}</span></div>
        <p class="plugin-description">{{ plugin.description || '暂无插件说明' }}</p>
        <div class="plugin-meta"><span>{{ typeName(plugin.type) }}</span><span>作者：{{ plugin.author || '未知' }}</span><span v-if="plugin.is_protected">核心插件</span><span v-if="plugin.need_upgrade" class="upgrade-label">可升级</span></div>
        <div class="plugin-actions">
          <button v-if="plugin.readme" class="btn btn-ghost btn-sm" @click="openReadme(plugin)">文档</button>
          <button v-if="!plugin.is_installed" class="btn btn-primary btn-sm" :disabled="busyCode === plugin.code" @click="action(plugin, 'install')">安装</button>
          <template v-else><button v-if="Object.keys(plugin.config || {}).length" class="btn btn-ghost btn-sm" :disabled="busyCode === plugin.code" @click="openConfig(plugin)">配置</button><button v-if="plugin.need_upgrade" class="btn btn-ghost btn-sm" :disabled="busyCode === plugin.code" @click="action(plugin, 'upgrade', `确定升级「${plugin.name}」？`)">升级</button><button v-if="plugin.is_enabled" class="btn btn-ghost btn-sm" :disabled="busyCode === plugin.code" @click="action(plugin, 'disable')">禁用</button><button v-else class="btn btn-primary btn-sm" :disabled="busyCode === plugin.code" @click="action(plugin, 'enable')">启用</button><button v-if="!plugin.is_enabled" class="btn btn-danger btn-sm" :disabled="busyCode === plugin.code" @click="action(plugin, 'uninstall', `确定卸载「${plugin.name}」？插件数据可能被清除。`)">卸载</button></template>
          <button v-if="!plugin.is_installed && plugin.can_be_deleted" class="btn btn-danger btn-sm" :disabled="busyCode === plugin.code" @click="action(plugin, 'delete', `确定永久删除「${plugin.name}」的插件文件？`)">删除</button>
        </div>
      </article>
    </div>
    <div v-if="modal.type" class="modal-backdrop" @click.self="modal.type = ''"><section class="modal-card"><div class="panel-head"><div><h2>{{ modal.type === 'config' ? `配置 ${modal.plugin.name}` : modal.plugin.name }}</h2><p v-if="modal.type === 'config'">配置只对当前插件生效。</p></div><button class="btn btn-ghost" @click="modal.type = ''">关闭</button></div><SmartEditor v-if="modal.type === 'config'" v-model="configModel" :fields="configFields" /><pre v-else class="readme-content">{{ modal.plugin.readme }}</pre><div v-if="modal.type === 'config'" class="modal-actions"><button class="btn btn-primary" :disabled="busyCode === modal.plugin.code" @click="saveConfig">{{ busyCode === modal.plugin.code ? '保存中…' : '保存配置' }}</button></div></section></div>
    <div v-if="toast.text" class="toast" :class="{ error: toast.type === 'error' }">{{ toast.text }}</div>
  </section>
</template>

// admin-src/src/pages/PluginManagement.tsx
import { useEffect, useMemo, useRef, useState } from "react";
import { CreditCard, FileText, Puzzle, RefreshCw, Settings2, Upload } from "lucide-react";
import { toast } from "sonner";

import { SmartEditor, type EditorField, type EditorModel, type EditorOption } from "@/components/SmartEditor";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { get, post } from "@/services/http";
import {
  ConfirmAction,
  EmptyState,
  MetricCard,
  MetricGrid,
  PageDialog,
  PageHeader,
  PageShell,
  SelectField,
  errorMessage,
} from "@/pages/react-page-helpers";

interface PluginType { value: string; label: string; icon?: string }
interface PluginConfigItem {
  value?: unknown;
  label?: string;
  placeholder?: string;
  description?: string;
  type?: string;
  options?: EditorOption[] | Record<string, string>;
}
interface PluginRecord {
  code: string;
  name: string;
  version?: string;
  description?: string;
  author?: string;
  type?: string;
  is_installed?: boolean;
  is_enabled?: boolean;
  is_protected?: boolean;
  need_upgrade?: boolean;
  can_be_deleted?: boolean;
  readme?: string;
  config?: Record<string, unknown>;
}

function normalizeOptions(options: PluginConfigItem["options"]): EditorOption[] {
  if (Array.isArray(options)) return options.map((option) => typeof option === "object" ? option : { value: option, label: String(option) });
  return Object.entries(options || {}).map(([value, label]) => ({ value, label }));
}

export default function PluginManagement() {
  const [plugins, setPlugins] = useState<PluginRecord[]>([]);
  const [types, setTypes] = useState<PluginType[]>([]);
  const [loading, setLoading] = useState(true);
  const [busyCode, setBusyCode] = useState("");
  const [keyword, setKeyword] = useState("");
  const [typeFilter, setTypeFilter] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [uploading, setUploading] = useState(false);
  const [dialog, setDialog] = useState<{ type: "" | "readme" | "config"; plugin: PluginRecord | null }>({ type: "", plugin: null });
  const [configModel, setConfigModel] = useState<EditorModel>({});
  const [configFields, setConfigFields] = useState<EditorField[]>([]);
  const uploadInput = useRef<HTMLInputElement>(null);

  const filtered = useMemo(() => plugins.filter((plugin) => {
    const term = keyword.trim().toLowerCase();
    const matchesText = !term || `${plugin.name} ${plugin.code} ${plugin.description || ""} ${plugin.author || ""}`.toLowerCase().includes(term);
    const matchesType = !typeFilter || plugin.type === typeFilter;
    const matchesStatus = statusFilter === "all" || (statusFilter === "installed" ? plugin.is_installed : !plugin.is_installed);
    return matchesText && matchesType && matchesStatus;
  }), [keyword, plugins, statusFilter, typeFilter]);

  const counts = useMemo(() => ({
    all: plugins.length,
    installed: plugins.filter((item) => item.is_installed).length,
    enabled: plugins.filter((item) => item.is_enabled).length,
  }), [plugins]);

  async function load() {
    setLoading(true);
    try {
      const [pluginData, typeData] = await Promise.all([
        get<PluginRecord[]>("/plugin/getPlugins"),
        get<PluginType[]>("/plugin/types"),
      ]);
      setPlugins(Array.isArray(pluginData) ? pluginData : []);
      setTypes(Array.isArray(typeData) ? typeData : []);
    } catch (reason) {
      toast.error(errorMessage(reason));
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { void load(); }, []);

  async function runAction(plugin: PluginRecord, action: string) {
    setBusyCode(plugin.code);
    try {
      await post(`/plugin/${action}`, { code: plugin.code });
      const labels: Record<string, string> = { install: "安装", uninstall: "卸载", enable: "启用", disable: "禁用", upgrade: "升级", delete: "删除" };
      toast.success(`${labels[action] || "操作"}成功`);
      await load();
    } catch (reason) {
      toast.error(errorMessage(reason));
    } finally {
      setBusyCode("");
    }
  }

  async function openConfig(plugin: PluginRecord) {
    setBusyCode(plugin.code);
    try {
      const config = await get<Record<string, PluginConfigItem>>("/plugin/config", { code: plugin.code });
      setConfigModel(Object.fromEntries(Object.entries(config || {}).map(([key, item]) => [key, item.value])));
      setConfigFields(Object.entries(config || {}).map(([key, item]) => ({
        key,
        label: item.label || key,
        placeholder: item.placeholder,
        help: item.description,
        type: (item.type === "text" ? "textarea" : item.type === "string" ? "text" : item.type || "text") as EditorField["type"],
        options: normalizeOptions(item.options),
      })));
      setDialog({ type: "config", plugin });
    } catch (reason) {
      toast.error(errorMessage(reason));
    } finally {
      setBusyCode("");
    }
  }

  async function saveConfig() {
    if (!dialog.plugin) return;
    setBusyCode(dialog.plugin.code);
    try {
      await post("/plugin/config", { code: dialog.plugin.code, config: configModel });
      toast.success("插件配置已保存");
      setDialog({ type: "", plugin: null });
      await load();
    } catch (reason) {
      toast.error(errorMessage(reason));
    } finally {
      setBusyCode("");
    }
  }

  async function upload(event: React.ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];
    if (!file) return;
    if (!file.name.toLowerCase().endsWith(".zip")) {
      toast.error("仅支持 ZIP 插件包");
      event.target.value = "";
      return;
    }
    const body = new FormData();
    body.append("file", file);
    setUploading(true);
    try {
      await post("/plugin/upload", body);
      toast.success("插件上传成功");
      await load();
    } catch (reason) {
      toast.error(errorMessage(reason));
    } finally {
      setUploading(false);
      event.target.value = "";
    }
  }

  const typeName = (value?: string) => types.find((item) => item.value === value)?.label || (value === "payment" ? "支付方式" : "功能");

  return (
    <PageShell>
      <PageHeader
        title="插件管理"
        description="安装、启用和配置功能扩展与支付插件。"
        action={
          <>
            <Input ref={uploadInput} className="hidden" type="file" accept=".zip,application/zip" onChange={upload} />
            <Button disabled={uploading} onClick={() => uploadInput.current?.click()}><Upload />{uploading ? "上传中…" : "上传插件"}</Button>
          </>
        }
      />

      <MetricGrid className="xl:grid-cols-3">
        <MetricCard label="全部插件" value={counts.all} hint="当前可用扩展" />
        <MetricCard label="已安装" value={counts.installed} hint="已写入系统" />
        <MetricCard label="已启用" value={counts.enabled} hint="正在运行" />
      </MetricGrid>

      <Card>
        <CardContent className="grid gap-3 pt-6 lg:grid-cols-[minmax(240px,1fr)_220px_180px_auto]">
          <Input value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder="插件名称、代码或描述" />
          <SelectField label="" value={typeFilter} onValueChange={setTypeFilter} options={[{ value: "", label: "全部类型" }, ...types.map((item) => ({ value: item.value, label: `${item.icon || ""} ${item.label}`.trim() }))]} />
          <SelectField label="" value={statusFilter} onValueChange={setStatusFilter} options={[{ value: "all", label: "全部状态" }, { value: "installed", label: "已安装" }, { value: "available", label: "可安装" }]} />
          <Button variant="outline" disabled={loading} onClick={load}><RefreshCw className={loading ? "animate-spin" : ""} />刷新</Button>
        </CardContent>
      </Card>

      {loading ? <EmptyState>正在加载插件…</EmptyState> : !filtered.length ? <EmptyState>没有符合条件的插件</EmptyState> : (
        <div className="grid gap-4 xl:grid-cols-2">
          {filtered.map((plugin) => (
            <Card key={plugin.code} className="overflow-hidden">
              <CardHeader className="flex-row items-start gap-4">
                <div className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary">
                  {plugin.type === "payment" ? <CreditCard /> : <Puzzle />}
                </div>
                <div className="min-w-0 flex-1">
                  <div className="flex flex-wrap items-center gap-2"><CardTitle>{plugin.name}</CardTitle><Badge variant="outline">v{plugin.version || "—"}</Badge></div>
                  <code className="mt-1 block truncate text-xs text-muted-foreground">{plugin.code}</code>
                </div>
                <Badge variant={!plugin.is_installed || !plugin.is_enabled ? "secondary" : "default"}>
                  {!plugin.is_installed ? "未安装" : plugin.is_enabled ? "已启用" : "已禁用"}
                </Badge>
              </CardHeader>
              <CardContent className="space-y-4">
                <CardDescription className="min-h-10 leading-relaxed">{plugin.description || "暂无插件说明"}</CardDescription>
                <div className="flex flex-wrap gap-2 text-xs text-muted-foreground">
                  <Badge variant="secondary">{typeName(plugin.type)}</Badge>
                  <span>作者：{plugin.author || "未知"}</span>
                  {plugin.is_protected ? <Badge variant="outline">核心插件</Badge> : null}
                  {plugin.need_upgrade ? <Badge className="bg-amber-100 text-amber-900">可升级</Badge> : null}
                </div>
                <div className="flex flex-wrap gap-2 border-t pt-4">
                  {plugin.readme ? <Button variant="outline" size="sm" onClick={() => setDialog({ type: "readme", plugin })}><FileText />文档</Button> : null}
                  {!plugin.is_installed ? (
                    <Button size="sm" disabled={busyCode === plugin.code} onClick={() => runAction(plugin, "install")}>安装</Button>
                  ) : (
                    <>
                      {Object.keys(plugin.config || {}).length ? <Button variant="outline" size="sm" disabled={busyCode === plugin.code} onClick={() => openConfig(plugin)}><Settings2 />配置</Button> : null}
                      {plugin.need_upgrade ? <ConfirmAction destructive={false} confirmText="确认升级" title={`升级 ${plugin.name}`} description="升级前请确认当前配置已备份。" disabled={busyCode === plugin.code} onConfirm={() => runAction(plugin, "upgrade")}>升级</ConfirmAction> : null}
                      <Button variant={plugin.is_enabled ? "outline" : "default"} size="sm" disabled={busyCode === plugin.code} onClick={() => runAction(plugin, plugin.is_enabled ? "disable" : "enable")}>{plugin.is_enabled ? "禁用" : "启用"}</Button>
                      {!plugin.is_enabled ? <ConfirmAction title={`卸载 ${plugin.name}`} description="插件数据可能被清除，此操作请谨慎执行。" confirmText="确认卸载" disabled={busyCode === plugin.code} onConfirm={() => runAction(plugin, "uninstall")}>卸载</ConfirmAction> : null}
                    </>
                  )}
                  {!plugin.is_installed && plugin.can_be_deleted ? <ConfirmAction title={`永久删除 ${plugin.name}`} description="插件文件将从服务器删除且无法恢复。" confirmText="永久删除" disabled={busyCode === plugin.code} onConfirm={() => runAction(plugin, "delete")}>删除</ConfirmAction> : null}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      <PageDialog
        open={Boolean(dialog.type && dialog.plugin)}
        onOpenChange={(open) => !open && setDialog({ type: "", plugin: null })}
        title={dialog.type === "config" ? `配置 ${dialog.plugin?.name || "插件"}` : dialog.plugin?.name || "插件文档"}
        description={dialog.type === "config" ? "配置只对当前插件生效。" : "插件提供的使用说明。"}
        className="sm:max-w-3xl"
        footer={dialog.type === "config" ? <Button disabled={busyCode === dialog.plugin?.code} onClick={saveConfig}>{busyCode === dialog.plugin?.code ? "保存中…" : "保存配置"}</Button> : undefined}
      >
        {dialog.type === "config" ? (
          <SmartEditor value={configModel} fields={configFields} onChange={setConfigModel} />
        ) : (
          <ScrollArea className="max-h-[62vh] rounded-xl bg-muted/50 p-4"><pre className="whitespace-pre-wrap font-sans text-sm leading-7">{dialog.plugin?.readme || "暂无文档"}</pre></ScrollArea>
        )}
      </PageDialog>
    </PageShell>
  );
}
