// admin-src/src/pages/TicketManagement.vue
<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import AppIcon from '../components/AppIcon.vue';
import { adminApi, authToken, get, post } from '../services/http';

const LEVELS = { 0: ['低', ''], 1: ['中', 'waiting'], 2: ['高', 'danger'] };
const tickets = ref([]), loading = ref(false), busy = ref(null), selected = ref(null), showConversation = ref(false), replying = ref(false);
const filters = reactive({ keyword: '', status: 'all', reply_status: 'all', level: 'all' });
const page = reactive({ current: 1, size: 20, total: 0, last: 1 });
const toast = reactive({ text: '', type: 'success' });
const replyText = ref('');
const stats = computed(() => ({ page: tickets.value.length, waiting: tickets.value.filter(t => Number(t.status) === 0 && Number(t.reply_status) === 0).length, replied: tickets.value.filter(t => Number(t.reply_status) === 1).length, closed: tickets.value.filter(t => Number(t.status) === 1).length }));

function notify(text, type = 'success') { toast.text = text; toast.type = type; clearTimeout(notify.timer); notify.timer = setTimeout(() => toast.text = '', 2800); }
function time(v) { return v ? new Date(Number(v) * 1000).toLocaleString('zh-CN', { hour12: false }) : '-'; }
function level(t) { return LEVELS[Number(t.level)] || ['未知', 'off']; }
function query() { const q = new URLSearchParams({ current: String(page.current), pageSize: String(page.size) }); if (filters.status !== 'all') q.set('status', filters.status); if (filters.reply_status !== 'all') q.append('reply_status[]', filters.reply_status); if (filters.keyword.includes('@')) q.set('email', filters.keyword.trim()); else if (filters.keyword) { q.set('filter[0][id]', /^\d+$/.test(filters.keyword) ? 'id' : 'subject'); q.set('filter[0][value]', filters.keyword); } if (filters.level !== 'all') { const i = filters.keyword && !filters.keyword.includes('@') ? 1 : 0; q.set(`filter[${i}][id]`, 'level'); q.set(`filter[${i}][value]`, filters.level); } return q.toString(); }
async function fetchRaw(path) { const response = await fetch(adminApi(path), { headers: { Accept: 'application/json', Authorization: `Bearer ${authToken().replace(/^Bearer /, '')}` } }); const json = await response.json().catch(() => ({})); if (!response.ok || json.status === 'fail' || (json.code && Number(json.code) !== 0)) throw new Error(json.message || '请求失败'); return json; }
async function load(reset = false) { if (reset) page.current = 1; loading.value = true; try { const json = await fetchRaw(`/ticket/fetch?${query()}`); tickets.value = Array.isArray(json.data) ? json.data : []; page.total = Number(json.total || tickets.value.length); page.last = Math.max(1, Math.ceil(page.total / page.size)); } catch (e) { notify(e.message, 'error'); } finally { loading.value = false; } }
async function openTicket(ticket) { busy.value = ticket.id; try { selected.value = await get('/ticket/fetch', { id: ticket.id }); replyText.value = ''; showConversation.value = true; } catch (e) { notify(e.message, 'error'); } finally { busy.value = null; } }
async function reply() { const message = replyText.value.trim(); if (!message) return notify('请输入回复内容', 'error'); if (message.length > 10000) return notify('回复内容不能超过 10,000 字', 'error'); replying.value = true; try { await post('/ticket/reply', { id: selected.value.id, message }); notify('回复已发送，邮件通知已加入队列'); replyText.value = ''; selected.value = await get('/ticket/fetch', { id: selected.value.id }); await load(); } catch (e) { notify(e.message, 'error'); } finally { replying.value = false; } }
async function closeTicket(ticket = selected.value) { if (!confirm(`确定关闭工单 #${ticket.id}「${ticket.subject}」？关闭后用户不能继续回复。`)) return; busy.value = ticket.id; try { await post('/ticket/close', { id: ticket.id }); notify('工单已关闭'); if (selected.value?.id === ticket.id) { selected.value.status = 1; showConversation.value = false; } await load(); } catch (e) { notify(e.message, 'error'); } finally { busy.value = null; } }
async function copy(value, label) { await navigator.clipboard.writeText(value || ''); notify(`${label}已复制`); }
onMounted(() => load(true));
</script>

<template>
  <section class="page-stack">
    <div class="page-heading page-heading-row"><div><h1>工单管理</h1><p>处理用户咨询、跟踪待回复工单，并查看完整沟通记录。</p></div><button class="btn btn-ghost" :disabled="loading" @click="load()"><AppIcon name="RefreshCw" :size="16" />刷新工单</button></div>
    <div class="stat-grid ticket-stats"><article class="stat-card"><span>当前页工单</span><strong>{{ stats.page }}</strong></article><article class="stat-card"><span>等待回复</span><strong>{{ stats.waiting }}</strong></article><article class="stat-card"><span>已回复</span><strong>{{ stats.replied }}</strong></article><article class="stat-card"><span>已关闭</span><strong>{{ stats.closed }}</strong></article></div>
    <div class="ticket-toolbar">
      <label class="filter-input"><span>搜索</span><input v-model.trim="filters.keyword" placeholder="工单主题、ID 或完整用户邮箱" @keyup.enter="load(true)" /></label>
      <label class="field compact-field"><span>工单状态</span><select v-model="filters.status" @change="load(true)"><option value="all">全部状态</option><option value="0">处理中</option><option value="1">已关闭</option></select></label>
      <label class="field compact-field"><span>回复状态</span><select v-model="filters.reply_status" @change="load(true)"><option value="all">全部回复状态</option><option value="0">等待管理员</option><option value="1">管理员已回复</option></select></label>
      <label class="field compact-field"><span>优先级</span><select v-model="filters.level" @change="load(true)"><option value="all">全部优先级</option><option value="0">低</option><option value="1">中</option><option value="2">高</option></select></label>
      <button class="btn btn-ghost" @click="load(true)">查询</button>
    </div>
    <div v-if="loading" class="panel settings-loading">正在加载工单…</div><div v-else-if="!tickets.length" class="panel settings-loading">暂无符合条件的工单</div>
    <div v-else class="ticket-list">
      <article v-for="t in tickets" :key="t.id" class="panel ticket-card" :class="{ urgent: Number(t.level) === 2 && Number(t.status) === 0 }">
        <button class="ticket-main" @click="openTicket(t)"><span class="ticket-level" :class="level(t)[1]">{{ level(t)[0] }}</span><div><h2>{{ t.subject }}</h2><p>{{ t.user?.email || `用户 #${t.user_id}` }} · 工单 #{{ t.id }}</p></div></button>
        <div class="ticket-state"><span class="status-pill" :class="{ off: Number(t.status) === 1, waiting: Number(t.status) === 0 && Number(t.reply_status) === 0 }">{{ Number(t.status) === 1 ? '已关闭' : Number(t.reply_status) === 0 ? '等待回复' : '已回复' }}</span><small>更新 {{ time(t.updated_at) }}</small></div>
        <div class="ticket-actions"><button class="btn btn-primary btn-sm" :disabled="busy === t.id" @click="openTicket(t)">{{ Number(t.status) === 0 ? '查看并回复' : '查看记录' }}</button><button v-if="Number(t.status) === 0" class="btn btn-ghost btn-sm" :disabled="busy === t.id" @click="closeTicket(t)">关闭工单</button></div>
      </article>
    </div>
    <div class="pagination"><span>共 {{ page.total }} 条</span><button class="btn btn-ghost btn-sm" :disabled="page.current <= 1 || loading" @click="page.current--; load()">上一页</button><span>{{ page.current }} / {{ page.last }}</span><button class="btn btn-ghost btn-sm" :disabled="page.current >= page.last || loading" @click="page.current++; load()">下一页</button></div>
    <div v-if="showConversation && selected" class="modal-backdrop" @click.self="showConversation = false"><section class="modal-card ticket-conversation"><div class="panel-head"><div><h2>{{ selected.subject }}</h2><p>{{ selected.user?.email }} · 工单 #{{ selected.id }} · {{ level(selected)[0] }}优先级</p></div><button class="btn btn-ghost" @click="showConversation = false">关闭</button></div>
      <div class="ticket-user-summary"><span>用户<strong>{{ selected.user?.email }}</strong></span><span>套餐<strong>{{ selected.user?.plan?.name || `#${selected.user?.plan_id || '-'}` }}</strong></span><span>余额<strong>¥{{ Number(selected.user?.balance || 0).toFixed(2) }}</strong></span><button class="btn btn-ghost btn-sm" @click="copy(selected.user?.email, '邮箱')">复制邮箱</button></div>
      <div class="message-timeline"><div v-if="!selected.messages?.length" class="empty">暂无消息内容</div><article v-for="m in selected.messages" :key="m.id" :class="{ admin: m.is_from_admin }"><div><strong>{{ m.is_from_admin ? '管理员' : selected.user?.email }}</strong><small>{{ time(m.created_at) }}</small></div><p>{{ m.message }}</p></article></div>
      <div v-if="Number(selected.status) === 0" class="ticket-reply"><div class="reply-tools"><span>回复用户</span><small>{{ replyText.length }} / 10000</small></div><textarea v-model="replyText" rows="5" maxlength="10000" placeholder="输入回复内容；发送后系统会异步通知用户邮箱。" @keydown.ctrl.enter.prevent="reply" /><div class="modal-actions"><small>Ctrl + Enter 快速发送</small><button class="btn btn-ghost" @click="closeTicket(selected)">关闭工单</button><button class="btn btn-primary" :disabled="replying || !replyText.trim()" @click="reply">{{ replying ? '发送中…' : '发送回复' }}</button></div></div><div v-else class="ticket-closed-note">该工单已关闭，仅可查看历史消息。</div>
    </section></div><div v-if="toast.text" class="toast" :class="{ error: toast.type === 'error' }">{{ toast.text }}</div>
  </section>
</template>

// admin-src/src/pages/TicketManagement.tsx
import { useCallback, useEffect, useMemo, useState } from "react";
import { Copy, RefreshCw } from "lucide-react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { adminApi, authToken, get, post } from "@/services/http";
import {
    ConfirmAction,
    EmptyState,
    MetricCard,
    MetricGrid,
    PageDialog,
    PageHeader,
    PageShell,
    Pagination,
    Panel,
    SelectField,
    StatusBadge,
    errorMessage,
    formatUnixTime,
    type UnknownRecord,
} from "./react-page-helpers";

const LEVELS: Record<number, [string, "neutral" | "warning" | "danger"]> = {
    0: ["低", "neutral"],
    1: ["中", "warning"],
    2: ["高", "danger"],
};

export default function TicketManagement() {
    const [tickets, setTickets] = useState<UnknownRecord[]>([]);
    const [loading, setLoading] = useState(false);
    const [busy, setBusy] = useState<number | null>(null);
    const [selected, setSelected] = useState<UnknownRecord | null>(null);
    const [showConversation, setShowConversation] = useState(false);
    const [replying, setReplying] = useState(false);
    const [replyText, setReplyText] = useState("");
    const [filters, setFilters] = useState({
        keyword: "",
        status: "all",
        reply_status: "all",
        level: "all",
    });
    const [page, setPage] = useState({
        current: 1,
        size: 20,
        total: 0,
        last: 1,
    });
    const stats = useMemo(
        () => ({
            page: tickets.length,
            waiting: tickets.filter(
                (ticket) =>
                    Number(ticket.status) === 0 &&
                    Number(ticket.reply_status) === 0,
            ).length,
            replied: tickets.filter(
                (ticket) => Number(ticket.reply_status) === 1,
            ).length,
            closed: tickets.filter((ticket) => Number(ticket.status) === 1)
                .length,
        }),
        [tickets],
    );
    const level = (ticket: UnknownRecord) =>
        LEVELS[Number(ticket.level)] || (["未知", "neutral"] as const);

    const query = useCallback(
        (current: number) => {
            const queryParams = new URLSearchParams({
                current: String(current),
                pageSize: String(page.size),
            });
            if (filters.status !== "all")
                queryParams.set("status", filters.status);
            if (filters.reply_status !== "all")
                queryParams.append("reply_status[]", filters.reply_status);
            if (filters.keyword.includes("@"))
                queryParams.set("email", filters.keyword.trim());
            else if (filters.keyword) {
                queryParams.set(
                    "filter[0][id]",
                    /^\d+$/.test(filters.keyword) ? "id" : "subject",
                );
                queryParams.set("filter[0][value]", filters.keyword);
            }
            if (filters.level !== "all") {
                const index =
                    filters.keyword && !filters.keyword.includes("@") ? 1 : 0;
                queryParams.set(`filter[${index}][id]`, "level");
                queryParams.set(`filter[${index}][value]`, filters.level);
            }
            return queryParams.toString();
        },
        [filters, page.size],
    );
    const fetchRaw = async (path: string) => {
        const response = await fetch(adminApi(path), {
            headers: {
                Accept: "application/json",
                Authorization: `Bearer ${authToken().replace(/^Bearer /, "")}`,
            },
        });
        const json = (await response.json().catch(() => ({}))) as UnknownRecord;
        if (
            !response.ok ||
            json.status === "fail" ||
            (json.code && Number(json.code) !== 0)
        )
            throw new Error(String(json.message || "请求失败"));
        return json;
    };
    const load = useCallback(
        async (
            reset = false,
            requestedPage?: number,
            filterOverride?: typeof filters,
        ) => {
            const current = reset ? 1 : (requestedPage ?? page.current);
            setLoading(true);
            try {
                let queryString: string;
                if (filterOverride) {
                    const params = new URLSearchParams({
                        current: String(current),
                        pageSize: String(page.size),
                    });
                    if (filterOverride.status !== "all")
                        params.set("status", filterOverride.status);
                    if (filterOverride.reply_status !== "all")
                        params.append(
                            "reply_status[]",
                            filterOverride.reply_status,
                        );
                    if (filterOverride.keyword.includes("@"))
                        params.set("email", filterOverride.keyword.trim());
                    else if (filterOverride.keyword) {
                        params.set(
                            "filter[0][id]",
                            /^\d+$/.test(filterOverride.keyword)
                                ? "id"
                                : "subject",
                        );
                        params.set("filter[0][value]", filterOverride.keyword);
                    }
                    if (filterOverride.level !== "all") {
                        const index =
                            filterOverride.keyword &&
                            !filterOverride.keyword.includes("@")
                                ? 1
                                : 0;
                        params.set(`filter[${index}][id]`, "level");
                        params.set(
                            `filter[${index}][value]`,
                            filterOverride.level,
                        );
                    }
                    queryString = params.toString();
                } else queryString = query(current);
                const json = await fetchRaw(`/ticket/fetch?${queryString}`);
                const rows = Array.isArray(json.data) ? json.data : [];
                const total = Number(json.total || rows.length);
                setTickets(rows);
                setPage((previous) => ({
                    ...previous,
                    current,
                    total,
                    last: Math.max(1, Math.ceil(total / previous.size)),
                }));
            } catch (error) {
                toast.error(errorMessage(error));
            } finally {
                setLoading(false);
            }
        },
        [page.current, page.size, query],
    );
    useEffect(() => {
        void load(true);
    }, []); // eslint-disable-line react-hooks/exhaustive-deps

    const updateFilter = (
        key: keyof typeof filters,
        value: string,
        immediate = false,
    ) => {
        const next = { ...filters, [key]: value };
        setFilters(next);
        if (immediate) void load(true, 1, next);
    };
    const openTicket = async (ticket: UnknownRecord) => {
        setBusy(Number(ticket.id));
        try {
            setSelected(
                (await get("/ticket/fetch", {
                    id: ticket.id,
                })) as UnknownRecord,
            );
            setReplyText("");
            setShowConversation(true);
        } catch (error) {
            toast.error(errorMessage(error));
        } finally {
            setBusy(null);
        }
    };
    const reply = async () => {
        const message = replyText.trim();
        if (!message) return toast.error("请输入回复内容");
        if (message.length > 10000)
            return toast.error("回复内容不能超过 10,000 字");
        if (!selected) return;
        setReplying(true);
        try {
            await post("/ticket/reply", { id: selected.id, message });
            toast.success("回复已发送，邮件通知已加入队列");
            setReplyText("");
            setSelected(
                (await get("/ticket/fetch", {
                    id: selected.id,
                })) as UnknownRecord,
            );
            await load();
        } catch (error) {
            toast.error(errorMessage(error));
        } finally {
            setReplying(false);
        }
    };
    const closeTicket = async (ticket: UnknownRecord) => {
        setBusy(Number(ticket.id));
        try {
            await post("/ticket/close", { id: ticket.id });
            toast.success("工单已关闭");
            if (selected?.id === ticket.id) {
                setSelected((previous) =>
                    previous ? { ...previous, status: 1 } : null,
                );
                setShowConversation(false);
            }
            await load();
        } catch (error) {
            toast.error(errorMessage(error));
        } finally {
            setBusy(null);
        }
    };
    const copy = async (value: string, label: string) => {
        try {
            await navigator.clipboard.writeText(value || "");
            toast.success(`${label}已复制`);
        } catch {
            toast.error("复制失败，请手动复制");
        }
    };

    return (
        <PageShell>
            <PageHeader
                title="工单管理"
                description="处理用户咨询、跟踪待回复工单，并查看完整沟通记录。"
                action={
                    <Button
                        variant="outline"
                        disabled={loading}
                        onClick={() => void load()}
                    >
                        <RefreshCw />
                        刷新工单
                    </Button>
                }
            />
            <MetricGrid>
                <MetricCard label="当前页工单" value={stats.page} />
                <MetricCard label="等待回复" value={stats.waiting} />
                <MetricCard label="已回复" value={stats.replied} />
                <MetricCard label="已关闭" value={stats.closed} />
            </MetricGrid>
            <Panel>
                <div className="ticket-toolbar grid gap-3 xl:grid-cols-[1fr_11rem_12rem_10rem_auto] xl:items-end">
                    <div className="grid gap-2">
                        <span className="text-sm font-medium">搜索</span>
                        <Input
                            value={filters.keyword}
                            onChange={(event) =>
                                updateFilter("keyword", event.target.value)
                            }
                            placeholder="工单主题、ID 或完整用户邮箱"
                            onKeyDown={(event) =>
                                event.key === "Enter" && void load(true)
                            }
                        />
                    </div>
                    <SelectField
                        label="工单状态"
                        value={filters.status}
                        onValueChange={(value) =>
                            updateFilter("status", value, true)
                        }
                        options={[
                            { value: "all", label: "全部状态" },
                            { value: "0", label: "处理中" },
                            { value: "1", label: "已关闭" },
                        ]}
                    />
                    <SelectField
                        label="回复状态"
                        value={filters.reply_status}
                        onValueChange={(value) =>
                            updateFilter("reply_status", value, true)
                        }
                        options={[
                            { value: "all", label: "全部回复状态" },
                            { value: "0", label: "等待管理员" },
                            { value: "1", label: "管理员已回复" },
                        ]}
                    />
                    <SelectField
                        label="优先级"
                        value={filters.level}
                        onValueChange={(value) =>
                            updateFilter("level", value, true)
                        }
                        options={[
                            { value: "all", label: "全部优先级" },
                            { value: "0", label: "低" },
                            { value: "1", label: "中" },
                            { value: "2", label: "高" },
                        ]}
                    />
                    <Button variant="outline" onClick={() => void load(true)}>
                        查询
                    </Button>
                </div>
            </Panel>
            {loading ? (
                <Panel>
                    <EmptyState>正在加载工单…</EmptyState>
                </Panel>
            ) : tickets.length === 0 ? (
                <Panel>
                    <EmptyState>暂无符合条件的工单</EmptyState>
                </Panel>
            ) : (
                <div className="ticket-list space-y-3">
                    {tickets.map((ticket) => (
                        <Panel
                            key={ticket.id}
                            className={
                                Number(ticket.level) === 2 &&
                                Number(ticket.status) === 0
                                    ? "ring-destructive/40"
                                    : ""
                            }
                        >
                            <div className="flex flex-col gap-3 lg:flex-row lg:items-center">
                                <Button
                                    variant="ghost"
                                    className="ticket-main h-auto min-w-0 flex-1 justify-start p-0 text-left"
                                    onClick={() => void openTicket(ticket)}
                                >
                                    <StatusBadge tone={level(ticket)[1]}>
                                        {level(ticket)[0]}
                                    </StatusBadge>
                                    <div className="min-w-0">
                                        <h2 className="truncate font-semibold">
                                            {ticket.subject}
                                        </h2>
                                        <p className="truncate text-xs text-muted-foreground">
                                            {ticket.user?.email ||
                                                `用户 #${ticket.user_id}`}{" "}
                                            · 工单 #{ticket.id}
                                        </p>
                                    </div>
                                </Button>
                                <div className="ticket-state lg:text-right">
                                    <StatusBadge
                                        tone={
                                            Number(ticket.status) === 1
                                                ? "neutral"
                                                : Number(
                                                        ticket.reply_status,
                                                    ) === 0
                                                  ? "warning"
                                                  : "default"
                                        }
                                    >
                                        {Number(ticket.status) === 1
                                            ? "已关闭"
                                            : Number(ticket.reply_status) === 0
                                              ? "等待回复"
                                              : "已回复"}
                                    </StatusBadge>
                                    <small className="mt-1 block text-muted-foreground">
                                        更新{" "}
                                        {formatUnixTime(
                                            Number(ticket.updated_at),
                                        )}
                                    </small>
                                </div>
                                <div className="ticket-actions flex gap-2">
                                    <Button
                                        size="sm"
                                        disabled={busy === Number(ticket.id)}
                                        onClick={() => void openTicket(ticket)}
                                    >
                                        {Number(ticket.status) === 0
                                            ? "查看并回复"
                                            : "查看记录"}
                                    </Button>
                                    {Number(ticket.status) === 0 && (
                                        <ConfirmAction
                                            destructive={false}
                                            variant="outline"
                                            title="关闭工单"
                                            description={`确定关闭工单 #${ticket.id}「${ticket.subject}」？关闭后用户不能继续回复。`}
                                            confirmText="关闭工单"
                                            disabled={
                                                busy === Number(ticket.id)
                                            }
                                            onConfirm={() =>
                                                closeTicket(ticket)
                                            }
                                        >
                                            关闭工单
                                        </ConfirmAction>
                                    )}
                                </div>
                            </div>
                        </Panel>
                    ))}
                </div>
            )}
            <Pagination
                current={page.current}
                last={page.last}
                total={page.total}
                loading={loading}
                onChange={(current) => void load(false, current)}
            />
            <PageDialog
                open={showConversation && Boolean(selected)}
                onOpenChange={setShowConversation}
                title={String(selected?.subject || "工单详情")}
                description={
                    selected
                        ? `${selected.user?.email || `用户 #${selected.user_id}`} · 工单 #${selected.id} · ${level(selected)[0]}优先级`
                        : ""
                }
                className="sm:max-w-4xl"
            >
                {selected && (
                    <div className="space-y-4">
                        <div className="grid gap-2 rounded-lg bg-muted/50 p-3 sm:grid-cols-[1fr_1fr_1fr_auto]">
                            <span className="text-xs text-muted-foreground">
                                用户
                                <strong className="block text-sm text-foreground">
                                    {selected.user?.email}
                                </strong>
                            </span>
                            <span className="text-xs text-muted-foreground">
                                套餐
                                <strong className="block text-sm text-foreground">
                                    {selected.user?.plan?.name ||
                                        `#${selected.user?.plan_id || "-"}`}
                                </strong>
                            </span>
                            <span className="text-xs text-muted-foreground">
                                余额
                                <strong className="block text-sm text-foreground">
                                    ¥
                                    {Number(
                                        selected.user?.balance || 0,
                                    ).toFixed(2)}
                                </strong>
                            </span>
                            <Button
                                variant="outline"
                                size="sm"
                                onClick={() =>
                                    void copy(
                                        String(selected.user?.email || ""),
                                        "邮箱",
                                    )
                                }
                            >
                                <Copy />
                                复制邮箱
                            </Button>
                        </div>
                        <div className="message-timeline max-h-[42vh] space-y-3 overflow-y-auto rounded-lg border p-3">
                            {!selected.messages?.length ? (
                                <EmptyState>暂无消息内容</EmptyState>
                            ) : (
                                selected.messages.map(
                                    (message: UnknownRecord) => (
                                        <article
                                            key={message.id}
                                            className={`max-w-[85%] rounded-lg p-3 ${message.is_from_admin ? "ml-auto bg-primary text-primary-foreground" : "bg-muted"}`}
                                        >
                                            <div className="mb-2 flex justify-between gap-4 text-xs">
                                                <strong>
                                                    {message.is_from_admin
                                                        ? "管理员"
                                                        : selected.user?.email}
                                                </strong>
                                                <small
                                                    className={
                                                        message.is_from_admin
                                                            ? "text-primary-foreground/70"
                                                            : "text-muted-foreground"
                                                    }
                                                >
                                                    {formatUnixTime(
                                                        Number(
                                                            message.created_at,
                                                        ),
                                                    )}
                                                </small>
                                            </div>
                                            <p className="whitespace-pre-wrap text-sm">
                                                {message.message}
                                            </p>
                                        </article>
                                    ),
                                )
                            )}
                        </div>
                        {Number(selected.status) === 0 ? (
                            <div className="ticket-reply space-y-2">
                                <div className="flex justify-between text-sm">
                                    <span className="font-medium">
                                        回复用户
                                    </span>
                                    <small className="text-muted-foreground">
                                        {replyText.length} / 10000
                                    </small>
                                </div>
                                <Textarea
                                    value={replyText}
                                    onChange={(event) =>
                                        setReplyText(event.target.value)
                                    }
                                    rows={5}
                                    maxLength={10000}
                                    placeholder="输入回复内容；发送后系统会异步通知用户邮箱。"
                                    onKeyDown={(event) => {
                                        if (
                                            event.ctrlKey &&
                                            event.key === "Enter"
                                        ) {
                                            event.preventDefault();
                                            void reply();
                                        }
                                    }}
                                />
                                <div className="flex flex-wrap items-center justify-end gap-2">
                                    <small className="mr-auto text-muted-foreground">
                                        Ctrl + Enter 快速发送
                                    </small>
                                    <ConfirmAction
                                        destructive={false}
                                        variant="outline"
                                        title="关闭工单"
                                        description={`确定关闭工单 #${selected.id}「${selected.subject}」？关闭后用户不能继续回复。`}
                                        confirmText="关闭工单"
                                        onConfirm={() => closeTicket(selected)}
                                    >
                                        关闭工单
                                    </ConfirmAction>
                                    <Button
                                        disabled={replying || !replyText.trim()}
                                        onClick={() => void reply()}
                                    >
                                        {replying ? "发送中…" : "发送回复"}
                                    </Button>
                                </div>
                            </div>
                        ) : (
                            <p className="rounded-lg bg-muted p-3 text-sm text-muted-foreground">
                                该工单已关闭，仅可查看历史消息。
                            </p>
                        )}
                    </div>
                )}
            </PageDialog>
        </PageShell>
    );
}
